/**
 * HTML Dashboard Report Generator for issue-triage-cli
 * Generates a standalone, dark-themed HTML report for GitHub repository triage.
 */

function formatAsHTML(items = [], options = {}) {
  const repo = options.repository || 'GitHub Repository';
  const total = items.length;
  const staleCount = items.filter(i => i.isStale).length;
  const highPriorityCount = items.filter(i => (i.score || 0) >= 10).length;

  const rowsHtml = items.map((item, index) => `
    <tr class="${item.isStale ? 'stale-row' : ''}">
      <td>#${item.number}</td>
      <td><span class="badge ${item.isPR ? 'pr-badge' : 'issue-badge'}">${item.isPR ? 'PR' : 'Issue'}</span></td>
      <td><strong>${escapeHtml(item.title || '')}</strong></td>
      <td>${escapeHtml(item.author || 'unknown')}</td>
      <td><span class="score-pill score-${getScoreLevel(item.score)}">${item.score || 0}</span></td>
      <td>${(item.labels || []).map(l => `<span class="label-tag">${escapeHtml(l)}</span>`).join(' ')}</td>
      <td>${item.isStale ? '<span class="stale-tag">Stale</span>' : '<span class="active-tag">Active</span>'}</td>
    </tr>
  `).join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Issue Triage Dashboard — ${escapeHtml(repo)}</title>
  <style>
    :root {
      --bg: #0d1117;
      --card-bg: #161b22;
      --border: #30363d;
      --text: #c9d1d9;
      --text-muted: #8b949e;
      --accent: #58a6ff;
      --danger: #f85149;
      --warning: #d29922;
      --success: #3fb950;
    }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
      background: var(--bg);
      color: var(--text);
      margin: 0;
      padding: 2rem;
    }
    .header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      border-bottom: 1px solid var(--border);
      padding-bottom: 1rem;
      margin-bottom: 2rem;
    }
    h1 { margin: 0; font-size: 1.5rem; color: var(--text); }
    .stats {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
      gap: 1rem;
      margin-bottom: 2rem;
    }
    .stat-card {
      background: var(--card-bg);
      border: 1px solid var(--border);
      border-radius: 8px;
      padding: 1rem;
      text-align: center;
    }
    .stat-value { font-size: 2rem; font-weight: bold; color: var(--accent); }
    .stat-label { color: var(--text-muted); font-size: 0.875rem; }
    table {
      width: 100%;
      border-collapse: collapse;
      background: var(--card-bg);
      border: 1px solid var(--border);
      border-radius: 8px;
      overflow: hidden;
    }
    th, td {
      padding: 0.75rem 1rem;
      text-align: left;
      border-bottom: 1px solid var(--border);
    }
    th { background: #21262d; color: var(--text-muted); font-size: 0.85rem; }
    tr:hover { background: #1f242c; }
    .badge { padding: 2px 8px; border-radius: 12px; font-size: 0.75rem; font-weight: 600; }
    .pr-badge { background: #1f6feb22; color: #58a6ff; border: 1px solid #1f6feb; }
    .issue-badge { background: #23863622; color: #3fb950; border: 1px solid #238636; }
    .score-pill { padding: 2px 8px; border-radius: 10px; font-weight: bold; font-size: 0.85rem; }
    .score-high { background: #f8514933; color: var(--danger); }
    .score-med { background: #d2992233; color: var(--warning); }
    .score-low { background: #3fb95033; color: var(--success); }
    .label-tag { background: #21262d; border: 1px solid var(--border); border-radius: 4px; padding: 2px 6px; font-size: 0.75rem; }
    .stale-tag { color: var(--danger); font-weight: 600; }
    .active-tag { color: var(--success); }
    .footer { margin-top: 2rem; text-align: center; color: var(--text-muted); font-size: 0.8rem; }
  </style>
</head>
<body>
  <div class="header">
    <h1>📋 Issue Triage Dashboard — ${escapeHtml(repo)}</h1>
    <div>Generated by <code>issue-triage-cli v1.3.0</code></div>
  </div>
  <div class="stats">
    <div class="stat-card">
      <div class="stat-value">${total}</div>
      <div class="stat-label">Total Backlog Items</div>
    </div>
    <div class="stat-card">
      <div class="stat-value" style="color: var(--danger);">${highPriorityCount}</div>
      <div class="stat-label">High Priority</div>
    </div>
    <div class="stat-card">
      <div class="stat-value" style="color: var(--warning);">${staleCount}</div>
      <div class="stat-label">Stale Items</div>
    </div>
  </div>
  <table>
    <thead>
      <tr>
        <th>#</th>
        <th>Type</th>
        <th>Title</th>
        <th>Author</th>
        <th>Score</th>
        <th>Labels</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      ${rowsHtml || '<tr><td colspan="7" style="text-align:center;">No open issues or PRs found</td></tr>'}
    </tbody>
  </table>
  <div class="footer">
    Powered by <a href="https://github.com/Eliksey/issue-triage-cli" style="color: var(--accent);">issue-triage-cli</a> | OpenAI Codex Compatible
  </div>
</body>
</html>`;
}

function escapeHtml(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function getScoreLevel(score = 0) {
  if (score >= 10) return 'high';
  if (score >= 5) return 'med';
  return 'low';
}

module.exports = { formatAsHTML };
