/**
 * Formats issue triage results into GitHub Job Summary markdown syntax ($GITHUB_STEP_SUMMARY).
 * @param {Array} issues Array of scored issue objects
 * @returns {string} Markdown summary string
 */
function formatMarkdownSummary(issues) {
  const highPriority = issues.filter(i => i.score >= 50);
  const stale = issues.filter(i => i.isStale);

  let md = `## 📊 Issue Triage Summary (v1.5.0)\n\n`;
  md += `| Metric | Count |\n`;
  md += `| :--- | :---: |\n`;
  md += `| **Total Issues Scored** | \`${issues.length}\` |\n`;
  md += `| **High Priority (≥50)** | \`${highPriority.length}\` |\n`;
  md += `| **Stale (≥30d inactive)** | \`${stale.length}\` |\n\n`;

  md += `### 🔥 Top Priority Issues\n\n`;
  md += `| # | Title | Score | Status | Link |\n`;
  md += `| :---: | :--- | :---: | :---: | :--- |\n`;

  issues.forEach(item => {
    const statusBadge = item.isStale ? '⚠️ Stale' : (item.score >= 50 ? '🚨 High' : '🟢 Normal');
    md += `| #${item.number} | ${item.title} | **${item.score}** | ${statusBadge} | [View Issue](${item.html_url}) |\n`;
  });

  md += `\n---\n*Report generated by [issue-triage-cli](https://github.com/Eliksey/issue-triage-cli)*\n`;
  return md;
}

module.exports = { formatMarkdownSummary };
